name: Frappe App CI

on:
  push:
    branches:
      - dev-fix

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev python3-pip
        pip3 install -r requirements.txt

    - name: Run Tests
      run: cd ~/frappe-bench/ && bench --site test_site run-tests --app ecommerce_integrations --coverage
